"""wishlist added

Revision ID: b4138a1c5751
Revises: 61dc5f0128fb
Create Date: 2022-04-26 17:11:00.564226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4138a1c5751'
down_revision = '61dc5f0128fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wishlist', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wishlist')
    # ### end Alembic commands ###
