"""empty message

Revision ID: f094dab38991
Revises: b4138a1c5751
Create Date: 2022-04-27 11:14:15.255525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f094dab38991'
down_revision = 'b4138a1c5751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('author', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'author')
    # ### end Alembic commands ###
